optimized ping script
script optimized with  latency check

diff --git a/pingscript b/pingscript
--- a/pingscript
+++ b/pingscript
@@ -7,24 +7,25 @@ targets=(
    '8.8.8.8'        
    '8.8.4.4' 
    ) 
+# latency check (true|false)
+check=true
 # add max latency here
 max=500
-[ $# != 3 ] && echo "Usages: $0 <group> <intf> <status>" exit 1 
-group=$1 
-intf=$2 
-status=$3         
-for host in "${targets[@]}" 
-do    
-/bin/ping -n -c 1 -W 1 -w 1 -i 0.2 -I $intf $host &> /dev/null  
-if [ $? == 0 ]     
-then
-#check latency
-latency=$(/bin/ping -n -c 4 -W 2 -w 1 -i 0.2 -I $intf $host | tail -1| awk -F '/' '{print $5}')
+[ $# != 3 ] && echo "Usages: $0 <group> <intf> <status>" exit 1
+group=$1
+intf=$2
+status=$3
+for host in "${targets[@]}"
+do
+read latency < <(/bin/ping -n -c 4 -W 1 -w 1 -i 0.2 -I $intf $host | tail -1 | awk -F '/' '{print $5}')
+if [[ ${PIPESTATUS[0]} == 0 ]]; then
 strip=$(echo ${latency%.*})
-[ $strip -gt $max ] && exit 1
+[[ $check = "true" ]] && [[ $strip -gt $max ]] && continue
 #end check latency
-exit 0    
-fi    
-done 
-# fail 
+echo "good $strip $max"
+exit 0
+fi
+done
+# fail
 exit 1
+
